kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: frontend
    project: expense
    tier: web
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: web
  # pod definition
  template:
    metadata:
      labels:
        component: frontend
        project: expense
        tier: web
    spec:
      containers:
      - name: frontend
        image: saikumar718/frontend:{{ .Values.deployment.imageVersion }}
        volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
         name: frontend
         items:
          - key: nginx.conf
            path: nginx.conf
        # envFrom:
        # - configMapRef:
        #    name: frontend